export enum FaseActual {
    FASE_GRUPOS="FASE_GRUPOS",FINAL="FINAL",SEMIFINAL="SEMIFINAL",CUARTOS="CUARTOS",
    OCTAVOS="OCTAVOS",DIECISEISAVOS="DIECISEISAVOS",TREINTAIDOSAVOS="TREINTAIDOSAVOS",ELIMINATORIAS_GRUPOS="ELIMINATORIAS_GRUPOS"
}